apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
spec:
  ports:
    - port: 3200
      name: otpl-tempo
      protocol: TCP
      targetPort: otpl-tempo
    - port: 4317
      name: otpl-grpc
      protocol: TCP
      targetPort: otpl-grpc
  selector:
    app: tempo
  sessionAffinity: None
  type: ClusterIP
---
