apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-server-conf
  labels:
    name: collector-server-conf
  namespace: monitoring
data:
  collector.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:

    exporters:
      prometheusremotewrite:
        endpoint: "http://prometheus:9090/api/v1/write"
        resource_to_telemetry_conversion:
          enabled: true
        tls:
          insecure: true

      otlp:
        endpoint: tempo:4317
        tls:
          insecure: true

      otlphttp:
        endpoint: "http://loki:3100/otlp"
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
---