apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    name: grafana-config
  namespace: monitoring
data:
  datasources.yaml: |-
    apiVersion: 1

    datasources:

      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        editable: true

      - name: tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        editable: true
        jsonData:
          tracesToLogsV2:
            datasourceUid: 'loki'
            spanStartTimeShift: '-10m'
            spanEndTimeShift: '10m'
            tags: [{ key: 'service.name', value: 'service_name' }]
            filterByTraceID: false
            filterBySpanID: false
            customQuery: true
            query: '{ $${__tags} } | TraceId="$${__trace.traceId}"'
          serviceMap:
            datasourceUid: 'prometheus'
          nodeGraph:
            enabled: true

      - name: loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: true
        jsonData:
          derivedFields:
            - datasourceName: Tempo
              type: Label
              matcherLabel: "TraceId"
              name: TraceId
              url: "$${__value.raw}"
              datasourceUid: tempo
---
